### ISSUE TITLE
Not an Editor command: AcidInit

### ISSUE THREAD

**Issue by ibarrick** [clojure-vim/acid.nvim#11]
I'm getting this error everytime I open a file. I've tried removing and reinstalling the plugin. Any idea what this could be?

**Comment by hkupty** [comment]
Hi @ibarrick.

Acid.nvim is a remote plugin, so you must run `:UpdateRemotePlugins` after installing it.

I'll update the Readme.

Cheers!

**Comment by ibarrick** [comment]
Thanks! I knew I had this issue before but I couldn't remember how I had fixed it.
