### ISSUE TITLE
Docs and usage functions

### ISSUE THREAD

**Issue by ibarrick** [clojure-vim/acid.nvim#12]
K appears to work but only for some functions, and 'gu' opens up a quickfix window that shows nothing for any functions. Am I missing something obvious?

**Comment by hkupty** [comment]
Hi, sorry for taking this long to answer. I hope this is issue is solved by itself or was solved through the course of acid's development.

Nonetheless, this will for sure be solved by #31.

Thanks for support and interest on acid.nvim!

Cheers,
Henry

**Comment by hkupty** [comment]
Lua port is merged and #35 supersedes this one, so I'll close it.

However, if I forgot something, feel free to reopen it.

Cheers,
Henry
