### ISSUE TITLE
Specify :connect port

### ISSUE THREAD

**Issue by Quantisan** [clojure-vim/acid.nvim#19]
I can send a pull request and would appreciate some pointer. How can we enable specifying a port number manually ala `$ lein repl :connect 5555`?

**Comment by hkupty** [comment]
Hi! Sorry for taking long to answer.

It'd be awesome if you could. There are three places you'll need to change (probably refactor to simplify), all of them on `__init__.py`:
* The command function
* The acid_command function
* The context function

All of those try to get the url locally. What I suggest is to have some sort of cache that matches pwd with a url (host:port). If it misses, remove from cache.

If you need any more guidance or support, please tell me.

Cheers,
Henry

**Comment by hkupty** [comment]
Hi,
This issue is a bit old now, but nonetheless it'll be solved by #31. I hope this is still of your interest.

Thanks for the support,
Henry

**Comment by Quantisan** [comment]
thanks!

**Comment by hkupty** [comment]
Just merged the port to lua.
It deals with connections on a slightly different way. Would you mind testing the new version and giving some feedback? Also, if it does fix your use-case, let me know so I can close this issue.

Thanks!

**Comment by hkupty** [comment]
I'll close this since the feature exists on the lua version now. Feel free to reopen or open a new one if you still have issues.

Cheers,
