### ISSUE TITLE
Boot support

### ISSUE THREAD

**Issue by thiru** [clojure-vim/acid.nvim#20]
Is it possible to use this with boot rather than leiningen?

**Comment by hkupty** [comment]
I've never tried, but should be completely possible.

It only requires a `.nrepl-port` file to connect to the nrepl. I'm not sure
how boot deals with the repl, but as long as a nrepl port is open, acid can
make use of it.

If boot exposes a different file, I can add a handler to that as well.

Of course you'll have to take a look at how to use cider-nrepl and
refactor-nrepl on boot.

Cheers,
Henry

**Comment by SevereOverfl0w** [comment]
Boot works fine with acid

**Comment by thiru** [comment]
Thanks for the quick response @hkupty!

@SevereOverfl0w would you mind sharing how you set it up?  I'm pretty new to Clojure.

**Comment by SevereOverfl0w** [comment]
The easiest way is to use my vim-jack-in project and the `:Boot ` command within to start a cider repl.

The long way is the cider task you can find on the boot wiki. From there, acid works like normal.

On 11 January 2018 20:28:12 GMT+00:00, Thiru <notifications@github.com> wrote:
>Thanks for the quick response @hkupty!
>
>@SevereOverfl0w would you mind sharing how you set it up?  I'm pretty
>new to Clojure.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/clojure-vim/acid.nvim/issues/20#issuecomment-357051440

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by thiru** [comment]
Awesome thank you, will check that out!!
