### ISSUE TITLE
Feature request: a simple REPL prompt in the command area

### ISSUE THREAD

**Issue by daveyarwood** [clojure-vim/acid.nvim#38]
Typing into my buffer and eval-ing with `cpp` is great, but I'm finding myself wanting an equivalent to Fireplace's `cqp` (FireplacePrompt), which lets you enter a form in the command area and then shows you the result right there in the command area, without affecting your buffer at all.

`:call AcidInsertEval()` almost provides this, except that it inserts the result into the buffer instead of showing it to you in the command area.

`:call AcidInsertEval()` also runs within the `user=>` namespace, which is non-ideal, I think, because I usually want the prompt to have the same context as the buffer I'm editing. What would be better is if this REPL prompt were connected to the same namespace that you have currently required / the file you're editing.

**Comment by hkupty** [comment]
Done! :)
