### ISSUE TITLE
Feature request: an option to disable "go to definition"

### ISSUE THREAD

**Issue by daveyarwood** [clojure-vim/acid.nvim#53]
I've grown quite used to using ctags to manage "go to definition," to the extent that I prefer it over nREPL-based "go to definition," even if nREPL-based "go to definition" is more precise. The key thing is that I often edit Clojure code without being connected to a REPL, and I need "go to definition" to work in those moments. ctags allow me to do that in a "good enough" sort of way.

Would it be feasible to add something like a `g:acid_disable_go_to_definition`, which makes acid not remap `<C-]>`?

I see that there is a [`g:acid_no_default_keymappings`](https://github.com/clojure-vim/acid.nvim/blob/e8fec9276f2ff69e3ea10533065e7ff947563495/doc/acid.txt#L105), but that's not ideal because I would then need to maintain my own set of acid keybindings (for everything else acid provides) identical to the defaults, and keep up with any changes, etc. instead of the plugin ensuring that the keybindings stay up to date with the implementations.

**Comment by hkupty** [comment]
I believe I'd better remap to `gd` or `cgd` than `<C-]>`. Wdyt?

**Comment by daveyarwood** [comment]
I'm not familiar with `gd`, but based on [this](https://vim.fandom.com/wiki/Go_to_definition_using_g), it looks like it might be the better choice, since it looks like `<C-]>` might be specifically for tags.

**Comment by hkupty** [comment]
Nice.

Care to open a pr for that? Otherwise I will do that tomorrow morning.

Cheers,
Henry John Kupty

**Comment by daveyarwood** [comment]
Sure, I'm happy to take a stab at it tonight!
