### ISSUE TITLE
No request handler registered for acid:function:AcidGetNs

### ISSUE THREAD

**Issue by daveyarwood** [clojure-vim/acid.nvim#56]
After updating today, I get the following error when I run `:AcidRequire`:

```
Error detected while processing :
E5105: Error while calling lua chunk: ...me/dave/.vim/bundle/acid.nvim//lua/acid/features.lua:88: Vim(let):no request handler registered for "/home/dave/.vim/bundle/acid.nvim/rplugin/python3/acid:function:AcidGetNs"
```

**Comment by hkupty** [comment]
I believe you must run `:UpdateRemotePlugins` as I might have changed this
fn signature...

If that doesn't help then please let me know.

**Comment by daveyarwood** [comment]
I have vim-plug set up to do this automatically:

```
Plug 'clojure-vim/acid.nvim', { 'do': ':UpdateRemotePlugins' }
```

I had that some thought, that maybe the remote plugin had somehow gotten out of sync, so I ran `:UpdateRemotePlugins` manually just in case, then restarted vim and tried again. Same result.

**Comment by hkupty** [comment]
Sorry for the delay to reply.

Are you using the most recent pynvim (previous neovim python pkg)?

I believe you might be using a version that doesn't support the `nvim_exec_lua` api command, which bypasses the viml interpretation.

I'll make sure the old version is available as a fallback.

**Comment by daveyarwood** [comment]
I ran the following:

```
sudo pip install pynvim --upgrade
sudo pip3 install pynvim --upgrade
```

Then restarted vim and tried again. Same result.

It looks like I've upgraded to pynvim 0.3.2.

**Comment by daveyarwood** [comment]
I ran `:CheckHealth` and everything passed except that it looks like my `neovim` Node.js package is out of date, which doesn't seem like it would have an impact on the behavior of acid.nvim, but thought I'd mention it anyway.

```
## Node.js provider (optional)
  - INFO: Node.js: v6.17.1
  - INFO: Neovim node.js host: /usr/lib/node_modules/neovim/bin/cli.js
  - WARNING: Package "neovim" is out-of-date. Installed: 4.2.1, latest: 4.5.0
    - ADVICE:
      - Run in shell: npm install -g neovim
```

EDIT: After running `sudo npm install -g neovim`, restarting vim and trying again, the problem persists. I ran `:CheckHealth` again and everything is passing.

**Comment by hkupty** [comment]
This is weird. I'm unable to reproduce your error. I'm using neovim `v0.3.4` and `v0.4.0` on my tests. Both work correctly. What version of neovim are you using?

**Comment by daveyarwood** [comment]
```
$ nvim --version
NVIM v0.4.0-dev
Build type: RelWithDebInfo
Lua 5.1
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-w6baZc/neovim-0.4.0+ubuntu1+git201904072024-c5e8924-eada8be/build/config -I/build/neovim-w6baZc/neovim-0.4.0+ubuntu1+git201904072024-c5e8924-eada8be/src -I/build/neovim-w6baZc/neovim-0.4.0+ubuntu1+git201904072024-c5e8924-eada8be/.deps/usr/include -I/usr/include -I/build/neovim-w6baZc/neovim-0.4.0+ubuntu1+git201904072024-c5e8924-eada8be/build/src/nvim/auto -I/build/neovim-w6baZc/neovim-0.4.0+ubuntu1+git201904072024-c5e8924-eada8be/build/include
Compiled by buildd@lcy01-amd64-006

Features: +acl +iconv +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

Good thought about the neovim version. Maybe the issue is that I'm using a bleeding edge neovim that introduces a bug?

```
$ apt-cache policy neovim
neovim:
  Installed: 0.4.0+ubuntu1+git201904072024-c5e8924-eada8be-9ca834b~ubuntu16.04.1
  Candidate: 0.4.0+ubuntu1+git201904072024-c5e8924-eada8be-9ca834b~ubuntu16.04.1
  Version table:
 *** 0.4.0+ubuntu1+git201904072024-c5e8924-eada8be-9ca834b~ubuntu16.04.1 500
        500 http://ppa.launchpad.net/neovim-ppa/unstable/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by daveyarwood** [comment]
After updating, I'm getting a slightly different, but seemingly related error message:

```
E5105: Error while calling lua chunk: ...me/dave/.vim/bundle/acid.nvim//lua/acid/features.lua:88: Vim:E117: Unknown function: AcidGetNs
```

**Comment by hkupty** [comment]
Its weird that it doesn't register the function and it doesn't give you errors. I'll commit a reversion of one change on a branch, related to the plugins class. If it fixes, good, if it doesn't, I might know what is the issue then, but it should give errors when running `:UpdateRemotePlugins` nonetheless.

**Comment by hkupty** [comment]
Please try the commit 97af790. If it doesn't fix, I'll try something else later on, but it would be related to the new optional parameter on the function.

**Comment by daveyarwood** [comment]
On that commit, I get another slightly different error when I run `:AcidRequire`:

```
Error detected while processing :
E5105: Error while calling lua chunk: ...me/dave/.vim/bundle/acid.nvim//lua/acid/features.lua:88: Vim(let):no request handler registered for "/home/dave/.vim/bundle/acid.nvim/rplugin/python3/acid:function:AcidGetNs"
```

**Comment by daveyarwood** [comment]
The issue is fixed for me after those latest two commits on the `fix/get-ns-issue` branch.

**Comment by hkupty** [comment]
Caching the connections module somehow breaks on init.

I'll defer back to the old `exec_lua`.

**Comment by hkupty** [comment]
@daveyarwood Could you test again?

**Comment by daveyarwood** [comment]
That fixed it :+1:
